---
# Build libvips from source
# Prerequisites: http://www.vips.ecs.soton.ac.uk/index.php?title=Build_on_Ubuntu
- name: build tools
  apt: pkg={{ item }} state=present
  with_items:
    - build-essential
    - libxml2-dev
    - libfftw3-dev
    - gettext
    - libgtk2.0-dev
    - python-dev
    - liblcms1-dev
    # FIXME: Couldn’t find library
    # - liboil-dev
    - libmagickwand-dev
    - libopenexr-dev
    - libcfitsio3-dev
    - gobject-introspection
    - flex
    - bison

- name: tools for build from Git sources
  apt: pkg={{ item }} state=present
  with_items:
    - automake
    - libtool
    - swig
    - gtk-doc-tools
    - libglib2.0-dev
    - git

# Get sources
- name: get source
  git: repo=https://github.com/jcupitt/libvips.git dest=/tmp/libvips version=7.36

# Build
# Install with prefix in order to not having to rely on $PATH environment
# variable which causes issues with Upstart scripts.
# Reference: https://github.com/jcupitt/libvips/issues/31#issuecomment-9145077
- name: build
  shell: chdir=/tmp/libvips/ creates={{ admin_home }}/vips/bin/vips
         ./bootstrap.sh; ./configure --prefix={{ admin_home }}/vips;
         make; sudo make install

- name: clean up
  file: path=/tmp/libvips state=absent

- name: enable VIPS in .bashrc
  lineinfile: dest='{{ admin_home }}/.bashrc'
              regexp='{{ item.regexp }}'
              line='{{ item.line }}'
              state=present
  with_items:
    - { regexp: '^export VIPSHOME',
        line: 'export VIPSHOME={{ admin_home }}/vips' }
    - { regexp: '^export LD_LIBRARY_PATH=[$]LD_LIBRARY_PATH:[$]VIPSHOME/lib',
        line: 'export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$VIPSHOME/lib' }
    - { regexp: '^export PATH=[$]PATH:[$]VIPSHOME/bin',
        line: 'export PATH=$PATH:$VIPSHOME/bin' }
    - { regexp: '^export PKG_CONFIG_PATH=[$]PKG_CONFIG_PATH:[$]VIPSHOME/lib/pkgconfig',
        line: 'export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:$VIPSHOME/lib/pkgconfig' }
    - { regexp: '^export MANPATH=[$]MANPATH:[$]VIPSHOME/man',
        line: 'export MANPATH=$MANPATH:$VIPSHOME/man' }
    - { regexp: '^export PYTHONPATH=[$]VIPSHOME/lib/python2.7/site-packages',
        line: 'export PYTHONPATH=$VIPSHOME/lib/python2.7/site-packages' }
