---
- name: deploy latest application code
  hosts: webservers
  remote_user: zoomhub
  sudo: yes
  tasks:
  - name: update service upstart script
    template: src=roles/web/templates/service.conf.j2
              dest=/etc/init/{{ service }}.conf

  - name: update app source
    git: repo={{ app_repo }} dest={{ app_root }} version={{ app_version }}
         force=no

  - name: npm update
    npm: path={{ app_root }} state=latest

  - name: run app
    service: name={{ service }} state=restarted
