---
- name: deploy latest application code
  hosts: webservers
  remote_user: root
  sudo: yes
  tasks:
  - name: get app source
    git: repo={{ app_repo }} dest={{ app_root }} version={{ app_version }}
         force=no

  - name: npm update
    npm: path={{ app_root }}

  - name: run app
    service: name={{ service }} state=restarted
